name: Github Pages deploy

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn run build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: build
          force_orphan: true
